# Linear Algebra with PyTorch
---

Let us begin by importing the necessary modules.

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### Determinant of a matrix: 
The determinant of matrix is calculated using the __torch.linalg.det()__ function. One thing to be noted is that the function accepts only a float matrix. Also, you can calculate the determinant of a square matrix only.

In [2]:
# determinant of a matrix
a = torch.randint(20, (4, 4)).double()
print(a)
print(torch.linalg.det(a))

tensor([[19., 13.,  9., 11.],
        [ 9., 19.,  8., 17.],
        [12., 12.,  7., 10.],
        [17., 16., 10.,  6.]], dtype=torch.float64)
tensor(-338.0000, dtype=torch.float64)


#### Inverse of a matrix:

The torch.inverse() function is used to calculate the inverse of a matrix. One thing to be noted is that not every matrix is invertible. In case you try to invert a singular matrix (determinant = 0), you will end up with a run time error. 

Hence, checking if a matrix is singular is a good exception handling method. 

In [3]:
a = torch.randint(20, (4, 4)).double()
if torch.linalg.det(a):
    print(torch.inverse(a))

tensor([[ 0.1099, -0.1697, -0.0205,  0.0194],
        [ 0.0471, -0.1016, -0.0718,  0.0797],
        [-0.0728,  0.0560,  0.0723, -0.0098],
        [-0.0033,  0.1307,  0.0019, -0.0229]], dtype=torch.float64)


In [4]:
# will result in an error as matrix 'b' is singular

b = torch.Tensor([[1,2,3],
                  [2,3,4],
                  [0,0,0]])
torch.inverse(b)

RuntimeError: inverse_cpu: U(3,3) is zero, singular U.

#### Norms:

The torch.linalg.norm() method is used to calculate the various types of norms of matrices and vectors.

Here are some of the most used norms within linear algebra.

* __L<sup>2</sup> norm__: Used to calculate the distance of a vector from the origin.

* __L<sup>1</sup> norm__: The L1 norm is used is used when the difference between zero and non-zero elements is very important. The value of the L1 norm increases *e* when the vector moves away from the origin by a value *e*.

* __L<sup>0</sup> norm__: The L0 norm is used to calculate the number of non-zero elements within a vector.

* __Infinity norm__: The infinity norm is used to calculate the maximum element within the vector. Similarly, the -infinity norm is used to calculate the value of the minimum element within the vector.

In [ ]:
v = torch.Tensor([3, 4, 1, 2, 0, 6, 3, 0, 5, 9, 0])
print('L2 norm =', torch.linalg.norm(v, ord = 2))
print('L1 norm =', torch.linalg.norm(v, ord = 1))
print('L0 norm =', torch.linalg.norm(v, ord = 0))
print('Inf norm =', torch.linalg.norm(v, ord = float('inf')))
print('-Inf norm =', torch.linalg.norm(v, ord = -float('inf')))

## Eignedecomposition:

### → A v = λ v  

Eigendecomposition can be used to decompose a given square matrix into eigenvalues and eigenvectors. Doing so allows us to analyze certain properties of the matrix that otherwise might not be visible to the practitioner at the first glance of the data matrix.  

Here are some of the properties of eigendecomposition:

* Any real symmetric matrix is guaranteed to have an eigendecomposition. However, the eigendecomposition might not be unique. The eigendecomposition is said to be unique only and only if all the eigenvalues are unique.

* If any of the eigenavlues are 0, then the matrix is a singular matrix.

* In case of positive semidefinite matrices (all eigenvalues either positive or 0), __x<sup>T</sup> A x >= 0__.

* In case of positive definite matrices, __x<sup>T</sup> A x = 0__.

Now, let us have a look at how to perform eigendecomposition using PyTorch. 

NOTE: 
> * Eigendecomposition is possible only for square matrices.
> * Regular eigendecomposition (torch.eig()) can return complex eigenvectors and eigenvalues. Hence, backpropagation is not possible in case of torch.eig. Use __torch.symeig()__ to be able to perform backpropagation on eigenvectors. Symmetric eigendecomposition is carried out for real, symmetric matrices.

In [9]:
# square asymmetric matrix
a = torch.Tensor([[1, 6, 5, 4],
                  [7, 3, 2, 1],
                  [3, 8, 9, 6],
                  [4, 5, 6, 7]])

# square symmetric matrix
b = torch.Tensor([[1, 2, 3, 4, 5],
                  [2, 3, 4, 5, 6],
                  [3, 4, 5, 6, 7],
                  [4, 5, 6, 7, 8],
                  [5, 6, 7, 8, 9]])

In [15]:
# regular eigendecomposition
eig_val, eig_vect = torch.eig(a, eigenvectors=True)
print('Eigenvalues =', eig_val)
print('Eigenvectors =', eig_vect)

Eigenvalues = tensor([[19.3617,  0.0000],
        [-3.7889,  0.0000],
        [ 1.5183,  0.0000],
        [ 2.9089,  0.0000]])
Eigenvectors = tensor([[ 0.3973,  0.6052, -0.0843, -0.1020],
        [ 0.2857, -0.7128, -0.3329, -0.5572],
        [ 0.6634,  0.3440,  0.7931, -0.0292],
        [ 0.5661, -0.0853, -0.5030,  0.8236]])


One thing to be noted is that in case of regular eigendecomposition, the eigenvalue is a __n x 2__ matrix. The first column of the matrices represents the real part of each eigenvalue, and the second column represents the imaginary part.

In [14]:
# symmetric eigendecomposition
symeig_val, symeig_vect = torch.symeig(b, eigenvectors=True)
print('Eigenvalues =', eig_val)
print('Eigenvectors =', eig_vect)

Eigenvalues = tensor([-1.8614e+00, -4.6570e-07,  4.4451e-08,  6.4121e-07,  2.6861e+01])
Eigenvectors = tensor([[ 0.7255,  0.4651,  0.0324, -0.4273,  0.2715],
        [ 0.4197, -0.5476,  0.5069,  0.3784,  0.3520],
        [ 0.1138, -0.3923, -0.8036, -0.0198,  0.4325],
        [-0.1920,  0.5669, -0.0429,  0.6138,  0.5130],
        [-0.4978, -0.0922,  0.3073, -0.5451,  0.5935]])


## Singular Value Decomposition:

### → A<sub>m x n</sub> = U<sub>m x m</sub> D<sub>m x n</sub> V<sub>n x n</sub>

As Prof. Gilbert Strang said, SVD is one of the most important equations in linear algebra. Built on the same idea as eigendecomposition, SVD addresses one major issue with eigendecomposition. 

> Eigendecomposition is only applicable to square matrices. Also, you get real eigenvalues only for non-singular matrices. 

> SVD on the other hand allows decomposition of rectangular matrices as well. And unlike eigendecomposition, SVD is possible for every matrix. 

Let us have a look at how to perform SVD using PyTorch.

In [72]:
# 4 x 6 matrix of floats
A = torch.randint(20, (4, 6)).double()

U, D, V = torch.svd(A)

print(A)
print('\nLeft singular vector =\n', U)
print('\nSingular values =\n', D)
print('\nRight singular vector =\n', V.T)

tensor([[ 6.,  5., 12., 16., 12.,  3.],
        [15.,  4.,  4.,  4., 13., 10.],
        [10.,  2.,  0.,  7.,  8.,  7.],
        [13., 13.,  2.,  6., 13., 13.]], dtype=torch.float64)

Left singular vector =
 tensor([[-0.4880,  0.8680,  0.0713, -0.0571],
        [-0.5226, -0.2856, -0.5606, -0.5754],
        [-0.3628, -0.1143, -0.4391,  0.8140],
        [-0.5976, -0.3897,  0.6985,  0.0556]], dtype=torch.float64)

Singular values =
 tensor([42.8254, 15.3217,  7.2010,  4.1690], dtype=torch.float64)

Right singular vector =
 tensor([[-0.5175, -0.3041, -0.2135, -0.3742, -0.5446, -0.3969],
        [-0.3450, -0.1369,  0.5544,  0.6271,  0.0472, -0.3993],
        [-0.4570,  0.8772,  0.0014,  0.0022, -0.1200,  0.0854],
        [-0.0267, -0.0566, -0.6899,  0.6754, -0.2233,  0.1189]],
       dtype=torch.float64)


In [86]:
A_regenerated = torch.mm(torch.mm(U, torch.diag(D)), V.t())
A_regenerated

tensor([[6.0000e+00, 5.0000e+00, 1.2000e+01, 1.6000e+01, 1.2000e+01, 3.0000e+00],
        [1.5000e+01, 4.0000e+00, 4.0000e+00, 4.0000e+00, 1.3000e+01, 1.0000e+01],
        [1.0000e+01, 2.0000e+00, 1.8787e-15, 7.0000e+00, 8.0000e+00, 7.0000e+00],
        [1.3000e+01, 1.3000e+01, 2.0000e+00, 6.0000e+00, 1.3000e+01, 1.3000e+01]],
       dtype=torch.float64)