# Linear Algebra with PyTorch
---

Let us begin by importing the necessary modules.

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#### Determinant of a matrix: 
The determinant of matrix is calculated using the __torch.linalg.det()__ function. One thing to be noted is that the function accepts only a float matrix. Also, you can calculate the determinant of a square matrix only.

In [2]:
# determinant of a matrix
a = torch.randint(20, (4, 4)).double()
print(a)
print(torch.linalg.det(a))

tensor([[ 7.,  7., 10., 12.],
        [10.,  2., 11.,  5.],
        [14.,  2.,  9., 10.],
        [12., 11.,  4., 11.]], dtype=torch.float64)
tensor(-5743., dtype=torch.float64)


#### Inverse of a matrix:

The torch.inverse() function is used to calculate the inverse of a matrix. One thing to be noted is that not every matrix is invertible. In case you try to invert a singular matrix (determinant = 0), you will end up with a run time error. 

Hence, checking if a matrix is singular is a good exception handling method. 

In [3]:
a = torch.randint(20, (4, 4)).double()
if torch.linalg.det(a):
    print(torch.inverse(a))

tensor([[-0.0323,  0.0832, -0.0156,  0.0447],
        [ 0.1613, -0.0614, -0.0510, -0.3205],
        [-0.4194,  0.0499,  0.4906,  0.7268],
        [ 0.0968, -0.0562, -0.1145, -0.0052]], dtype=torch.float64)


In [4]:
# will result in an error as matrix 'b' is singular

b = torch.Tensor([[1,2,3],
                  [2,3,4],
                  [0,0,0]])
torch.inverse(b)

RuntimeError: inverse_cpu: U(3,3) is zero, singular U.

#### Norms:

The torch.linalg.norm() method is used to calculate the various types of norms of matrices and vectors.

Here are some of the most used norms within linear algebra.

* __L<sup>2</sup> norm__: Used to calculate the distance of a vector from the origin.

* __L<sup>1</sup> norm__: The L1 norm is used is used when the difference between zero and non-zero elements is very important. The value of the L1 norm increases *e* when the vector moves away from the origin by a value *e*.

* __L<sup>0</sup> norm__: The L0 norm is used to calculate the number of non-zero elements within a vector.

* __Infinity norm__: The infinity norm is used to calculate the maximum element within the vector. Similarly, the -infinity norm is used to calculate the value of the minimum element within the vector.

In [5]:
v = torch.Tensor([3, 4, 1, 2, 0, 6, 3, 0, 5, 9, 0])
print('L2 norm =', torch.linalg.norm(v, ord = 2))
print('L1 norm =', torch.linalg.norm(v, ord = 1))
print('L0 norm =', torch.linalg.norm(v, ord = 0))
print('Inf norm =', torch.linalg.norm(v, ord = float('inf')))
print('-Inf norm =', torch.linalg.norm(v, ord = -float('inf')))

L2 norm = tensor(13.4536)
L1 norm = tensor(33.)
L0 norm = tensor(8.)
Inf norm = tensor(9.)
-Inf norm = tensor(0.)


## Eignedecomposition:

### → A v = λ v  

Eigendecomposition can be used to decompose a given square matrix into eigenvalues and eigenvectors. Doing so allows us to analyze certain properties of the matrix that otherwise might not be visible to the practitioner at the first glance of the data matrix.  

Here are some of the properties of eigendecomposition:

* Any real symmetric matrix is guaranteed to have an eigendecomposition. However, the eigendecomposition might not be unique. The eigendecomposition is said to be unique only and only if all the eigenvalues are unique.

* If any of the eigenavlues are 0, then the matrix is a singular matrix.

* In case of positive semidefinite matrices (all eigenvalues either positive or 0), __x<sup>T</sup> A x >= 0__.

* In case of positive definite matrices, __x<sup>T</sup> A x = 0__.

Now, let us have a look at how to perform eigendecomposition using PyTorch. 

NOTE: 
> * Eigendecomposition is possible only for square matrices.
> * Regular eigendecomposition (torch.eig()) can return complex eigenvectors and eigenvalues. Hence, backpropagation is not possible in case of torch.eig. Use __torch.symeig()__ to be able to perform backpropagation on eigenvectors. Symmetric eigendecomposition is carried out for real, symmetric matrices.

In [6]:
# square asymmetric matrix
a = torch.Tensor([[1, 6, 5, 4],
                  [7, 3, 2, 1],
                  [3, 8, 9, 6],
                  [4, 5, 6, 7]])

# square symmetric matrix
b = torch.Tensor([[1, 2, 3, 4, 5],
                  [2, 3, 4, 5, 6],
                  [3, 4, 5, 6, 7],
                  [4, 5, 6, 7, 8],
                  [5, 6, 7, 8, 9]])

In [7]:
# regular eigendecomposition
eig_val, eig_vect = torch.eig(a, eigenvectors=True)
print('Eigenvalues =', eig_val)
print('Eigenvectors =', eig_vect)

Eigenvalues = tensor([[19.3617,  0.0000],
        [-3.7889,  0.0000],
        [ 1.5183,  0.0000],
        [ 2.9089,  0.0000]])
Eigenvectors = tensor([[ 0.3973,  0.6052, -0.0843, -0.1020],
        [ 0.2857, -0.7128, -0.3329, -0.5572],
        [ 0.6634,  0.3440,  0.7931, -0.0292],
        [ 0.5661, -0.0853, -0.5030,  0.8236]])


One thing to be noted is that in case of regular eigendecomposition, the eigenvalue is a __n x 2__ matrix. The first column of the matrices represents the real part of each eigenvalue, and the second column represents the imaginary part.

In [8]:
# symmetric eigendecomposition
symeig_val, symeig_vect = torch.symeig(b, eigenvectors=True)
print('Eigenvalues =', eig_val)
print('Eigenvectors =', eig_vect)

Eigenvalues = tensor([[19.3617,  0.0000],
        [-3.7889,  0.0000],
        [ 1.5183,  0.0000],
        [ 2.9089,  0.0000]])
Eigenvectors = tensor([[ 0.3973,  0.6052, -0.0843, -0.1020],
        [ 0.2857, -0.7128, -0.3329, -0.5572],
        [ 0.6634,  0.3440,  0.7931, -0.0292],
        [ 0.5661, -0.0853, -0.5030,  0.8236]])


## Singular Value Decomposition:

### → A<sub>m x n</sub> = U<sub>m x m</sub> D<sub>m x n</sub> V<sub>n x n</sub>

As Prof. Gilbert Strang said, SVD is one of the most important equations in linear algebra. Built on the same idea as eigendecomposition, SVD addresses one major issue with eigendecomposition. 

> Eigendecomposition is only applicable to square matrices. Also, you get real eigenvalues only for non-singular matrices. 

> SVD on the other hand allows decomposition of rectangular matrices as well. And unlike eigendecomposition, SVD is possible for every matrix. 

Let us have a look at how to perform SVD using PyTorch.

In [9]:
# 4 x 6 matrix of floats
A = torch.randint(20, (4, 6)).double()

U, D, V = torch.svd(A)

print(A)
print('\nLeft singular vector =\n', U)
print('\nSingular values =\n', D)
print('\nRight singular vector =\n', V.T)

tensor([[11.,  3.,  9., 10.,  7.,  0.],
        [19.,  7., 18.,  8.,  7., 13.],
        [ 1., 18., 11.,  7., 16.,  0.],
        [ 5.,  8.,  7.,  8.,  8.,  3.]], dtype=torch.float64)

Left singular vector =
 tensor([[-0.3929,  0.1463, -0.8671, -0.2691],
        [-0.6667,  0.5986,  0.4332, -0.0971],
        [-0.5184, -0.7722,  0.2002, -0.3081],
        [-0.3639, -0.1547, -0.1428,  0.9073]], dtype=torch.float64)

Singular values =
 tensor([44.2519, 19.2735,  8.0998,  2.5879], dtype=torch.float64)

Right singular vector =
 tensor([[-0.4368, -0.4087, -0.5375, -0.3571, -0.4208, -0.2205],
        [ 0.5934, -0.5452,  0.1305, -0.0203, -0.4347,  0.3797],
        [-0.2248,  0.3570,  0.1477, -0.6107, -0.1206,  0.6424],
        [-0.2225,  0.0876, -0.4662,  0.6317, -0.0903,  0.5642]],
       dtype=torch.float64)


In [10]:
A_regenerated = torch.mm(torch.mm(U, torch.diag(D)), V.t())
A_regenerated

tensor([[ 1.1000e+01,  3.0000e+00,  9.0000e+00,  1.0000e+01,  7.0000e+00,
         -4.4504e-16],
        [ 1.9000e+01,  7.0000e+00,  1.8000e+01,  8.0000e+00,  7.0000e+00,
          1.3000e+01],
        [ 1.0000e+00,  1.8000e+01,  1.1000e+01,  7.0000e+00,  1.6000e+01,
         -1.1131e-14],
        [ 5.0000e+00,  8.0000e+00,  7.0000e+00,  8.0000e+00,  8.0000e+00,
          3.0000e+00]], dtype=torch.float64)

## Pseudoinverse: 

### → A<sup>+</sup> = V D<sup>+</sup> U<sup>T</sup>
### → x = A<sup>+</sup> y
(Denoted by A<sup>+</sup> for a rectangular matrix A)

While inverses can only be calculated for square, non-singular matrices, in many real-world cases, the matrices that we will be working with are generally rectangular in nature. 

One of the main advantages of having the inverse of a matrix A is that it allows us to solve the eqation __A x = y__ quite easily as __x = A<sup>-</sup> y__.

Thus, the concept of pseudoinverse in an inmportant one while working with matrices. 

While pseudoinverses will not give us the exact results, however, it ensures that the L<sub>2</sub> norm of the vector x (||x||<sub>2</sub>) will be minimum.

Here is to calculate pseudoinverses using PyTorch.

In [11]:
A = torch.randint(30, (5,6)).double()

A_plus = torch.pinverse(A)

# non-diagonal elements approach 0
print(A @ A_plus)

tensor([[ 1.0000e+00, -3.4694e-17, -2.0817e-17,  1.6653e-16,  7.3726e-18],
        [-2.4286e-16,  1.0000e+00, -4.6491e-16, -2.4980e-16,  4.0289e-16],
        [ 4.1633e-17, -9.7145e-17,  1.0000e+00, -3.7470e-16,  1.8995e-16],
        [-1.1796e-16,  6.9389e-18,  1.0408e-16,  1.0000e+00,  5.4600e-16],
        [-1.3878e-16,  8.3267e-17, -8.3267e-17, -6.9389e-17,  1.0000e+00]],
       dtype=torch.float64)


## Principal Component Analysis

One of the few uses of PCA is lossy compression of a matrix of data. What happens in the process of 'lossy compression, is that a matrix __A__ <sub>R<sup> M</sup></sub> is encoded into a matrix __C__ <sub>R<sup> L</sup></sub> such that L < M. This reduces the dimensionality of the matrix A, thus taking up less space within the memory.

However, one drawback is that upon decompression, some of the information might be lost, hence the term 'lossy'.

The following is the process of compression and decompression:

#### → C = f(A)
#### → A ≈ g(f(A))

Here, __f__ denotes the encoding function, and __g__ denotes the decoding function. 

The main idea behind PCA is to map a n-dimensional data to k-dimensions, such that __k < n__.

The newly obtained k-dimensional matrix is an orthogonal matrix.

The following method is used to implement SVD in PyTorch.

In [16]:
x = torch.randint(50, (4,5)).double()
x

tensor([[12.,  3., 47., 38., 48.],
        [ 0., 42., 29.,  1.,  8.],
        [48., 21., 19., 43.,  3.],
        [ 9., 48.,  8.,  5., 13.]], dtype=torch.float64)

In [20]:
u, s, v = torch.pca_lowrank(x)
print(u)
print(s)
print(v)

tensor([[-6.7462e-01, -5.2593e-01,  1.3526e-01,  5.0000e-01],
        [ 4.5018e-01, -2.7839e-01, -6.8545e-01,  5.0000e-01],
        [-2.8593e-01,  8.0368e-01, -1.4947e-01,  5.0000e-01],
        [ 5.1036e-01,  6.3415e-04,  6.9966e-01,  5.0000e-01]],
       dtype=torch.float64)
tensor([6.0807e+01, 4.6835e+01, 1.4705e+01, 5.6597e-28], dtype=torch.float64)
tensor([[-0.2833,  0.6890,  0.0507, -0.6269],
        [ 0.5818,  0.0777,  0.1402,  0.1135],
        [-0.3289, -0.3740, -0.7320, -0.1680],
        [-0.5744,  0.3053,  0.1037,  0.7007],
        [-0.3783, -0.5349,  0.6567, -0.2738]], dtype=torch.float64)


Now, projecting the matrix __x__ to first __k__ principal components can be done by: 

In [23]:
# let k = 3
x_k = torch.matmul(x, v[:, :3])
print(x_k)

tensor([[-57.1003, -23.1516,   2.0869],
        [ 11.2952, -11.5581,  -9.9812],
        [-33.4655,  39.1209,  -2.1000],
        [ 14.9547,   1.5100,  10.3862]], dtype=torch.float64)
