# PyTorch Basics
---
## Importing the Project Dependencies
---

The first step of a project is to import all the necessary dependencies.

In [2]:
import torch
import torch.nn as nn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Next, let us set the default device as the CUDA GPU.

In [3]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda', index=0)

We have successfully set the GPU as the default computational device for the tensors. The advantage of using GPU is that several tensors can be worked upon in parallel, hence increasing the processing speeds by several folds.

Now let us have a look at how to create and perform some elementary operations on tensors in PyTorch. 

## Tensors
---

In [6]:
# generating a tensor of dimensions 2x3x4
t = torch.Tensor(2,3,4)
t

tensor([[[1.7092e-04, 4.1428e-11, 1.7474e-04, 2.9574e-18],
         [6.7333e+22, 1.7591e+22, 1.7184e+25, 4.3222e+27],
         [6.1972e-04, 7.2443e+22, 1.7728e+28, 7.0367e+22]],

        [[1.8704e+20, 3.2944e-09, 1.3086e-11, 4.1545e+21],
         [6.7377e-10, 6.6756e+22, 6.3082e-10, 3.2686e+21],
         [2.7447e-06, 2.4830e-18, 7.7052e+31, 1.9447e+31]]])

In [7]:
# checking the shape of the tensor
print(t.size())
print(t.shape)

torch.Size([2, 3, 4])
torch.Size([2, 3, 4])


While both .size() and .shape return the same values, the only difference between these two is that .size() is a method while on the other hand .shape is an attribute of a tensor. 

In [11]:
# number of elements in a tensor- numel() method
print('Total number of elements within the tensor =', 
      ' \u00D7 '.join(map(str, t.shape)), '=', t.numel())

# number of dimensions that make up the tensor- dim() method
print('Number of dimensions in the tensor =', t.dim())

Total number of elements within the tensor = 2 × 3 × 4 = 24
Number of dimensions in the tensor = 3


Now let us have a look at some of the tensor mutations. Tensor mutations are special methods that modify/mutate a tensor in-place. The mutation methods are post-fixed by an underscore at the end. Let us see some examples here.

In [13]:
# .random_(n) - Replaces the values within a tensor w/ integersbetween range [0-n)
t.random_(10)

tensor([[[4., 7., 4., 5.],
         [1., 7., 9., 2.],
         [8., 6., 6., 7.]],

        [[3., 0., 2., 3.],
         [4., 2., 2., 4.],
         [5., 8., 3., 3.]]])

In [15]:
# .copy_(x) - Makes a copy of the tensor into another tensor x
y = torch.empty_like(t).copy_(t)
y

tensor([[[4., 7., 4., 5.],
         [1., 7., 9., 2.],
         [8., 6., 6., 7.]],

        [[3., 0., 2., 3.],
         [4., 2., 2., 4.],
         [5., 8., 3., 3.]]])

In [19]:
# .resize_() - Used to reshape the tensor 
y.resize_(4,2,3)

tensor([[[4., 7., 4.],
         [5., 1., 7.]],

        [[9., 2., 8.],
         [6., 6., 7.]],

        [[3., 0., 2.],
         [3., 4., 2.]],

        [[2., 4., 5.],
         [8., 3., 3.]]])

In [20]:
# .zero_() - Replaces all tensor elements with 0s
y.zero_()

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [21]:
# .fill_() - Used to replace all the tensor values with the fill argument value
y.fill_(5)

tensor([[[5., 5., 5.],
         [5., 5., 5.]],

        [[5., 5., 5.],
         [5., 5., 5.]],

        [[5., 5., 5.],
         [5., 5., 5.]],

        [[5., 5., 5.],
         [5., 5., 5.]]])

Now that we have seen some of the important mutation methods, let us have a look at one of the most important operations while working with tensors- Cloning a tensor.